package org.example.agentScope.util.skill;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Skill 环境配置管理器
 * <p>
 * 负责在 Git Skill 仓库克隆后动态生成 .env 配置文件。
 * 支持从 AI 中台集中管理配置，避免硬编码敏感信息。
 * <p>
 * 使用场景：
 * 1. 创建 Skill 时从中台获取配置并生成 .env
 * 2. 支持多环境配置（开发/测试/生产）
 * 3. 统一管理数据库连接、API Key 等敏感信息
 *
 * @author AgentScope-Team
 */
@Slf4j
@Component
public class SkillEnvConfigManager {

    @Autowired(required = false)
    private SkillConfigProperties skillConfig;

    /**
     * 配置缓存：repoUrl → 环境变量配置
     * 避免重复从中台获取配置
     */
    private final ConcurrentHashMap<String, Map<String, String>> configCache = new ConcurrentHashMap<>();

    /**
     * 默认配置模板（当无法从中台获取时使用）
     */
    private static final Map<String, String> DEFAULT_CONFIG_TEMPLATE = createDefaultConfig();
    
    private static Map<String, String> createDefaultConfig() {
        Map<String, String> config = new ConcurrentHashMap<>();
        
        // 数据库配置 - 数据查询统计库
        config.put("DB_HOST", "${DB_HOST:localhost}");
        config.put("DB_PORT", "${DB_PORT:3306}");
        config.put("DB_NAME", "${DB_NAME:menu_recommand}");
        config.put("DB_USER", "${DB_USER:root}");
        config.put("DB_PASSWORD", "${DB_PASSWORD:}");
        
        // 数据库配置 - DataPlatform 库
        config.put("DP_HOST", "${DP_HOST:localhost}");
        config.put("DP_PORT", "${DP_PORT:3306}");
        config.put("DP_NAME", "${DP_NAME:dp}");
        config.put("DP_USER", "${DP_USER:root}");
        config.put("DP_PASSWORD", "${DP_PASSWORD:}");
        
        // 数据库配置 - 对话存储库
        config.put("CONVERSATION_DB_HOST", "${CONVERSATION_DB_HOST:localhost}");
        config.put("CONVERSATION_DB_PORT", "${CONVERSATION_DB_PORT:3306}");
        config.put("CONVERSATION_DB_NAME", "${CONVERSATION_DB_NAME:conversation_db}");
        config.put("CONVERSATION_DB_USER", "${CONVERSATION_DB_USER:root}");
        config.put("CONVERSATION_DB_PASSWORD", "${CONVERSATION_DB_PASSWORD:}");
        
        // 企业微信开关
        config.put("WECOM_ENABLED", "${WECOM_ENABLED:true}");
        
        return config;
    }

    /**
     * 为指定的 Skill 仓库生成配置文件
     * <p>
     * 支持两种格式：
     * 1. .env 文件（Python dotenv 格式）- 默认
     * 2. config.yaml 文件（YAML 格式）- 推荐
     *
     * @param repoUrl   Git 仓库地址
     * @param workDir   工作目录（仓库根目录）
     * @param envName   环境名称（dev/test/prod），null 表示使用默认配置
     * @return 是否成功生成
     */
    public boolean generateEnvFile(String repoUrl, Path workDir, String envName) {
        // 优先尝试生成 YAML 配置
        return generateYamlConfig(repoUrl, workDir, envName);
    }

    /**
     * 生成 YAML 配置文件（推荐）
     *
     * @param repoUrl   Git 仓库地址
     * @param workDir   工作目录
     * @param envName   环境名称
     * @return 是否成功
     */
    private boolean generateYamlConfig(String repoUrl, Path workDir, String envName) {
        if (repoUrl == null || repoUrl.isBlank() || workDir == null) {
            log.warn("Invalid parameters for YAML config generation");
            return false;
        }

        try {
            // 1. 获取配置
            Map<String, String> config = getConfig(repoUrl, envName);

            // 2. 构建 YAML 数据结构
            Map<String, Object> yamlData = buildYamlStructure(config);

            // 3. 序列化为 YAML 字符串
            Yaml yaml = new Yaml();
            StringWriter writer = new StringWriter();
            
            // 添加注释头
            writer.write("# =============================================================================\n");
            writer.write("# Auto-generated by SkillEnvConfigManager\n");
            writer.write("# DO NOT commit this file to version control!\n");
            writer.write("# Generated at: " + java.time.Instant.now() + "\n");
            writer.write("# Repository: " + repoUrl + "\n");
            if (envName != null) {
                writer.write("# Environment: " + envName + "\n");
            }
            writer.write("# =============================================================================\n\n");
            
            yaml.dump(yamlData, writer);
            String yamlContent = writer.toString();

            // 4. 写入文件（同时生成 .env 和 config.yaml 以兼容）
            Path yamlPath = workDir.resolve("config").resolve("config.yaml");
            Path envPath = workDir.resolve("config").resolve(".env");
            
            // 确保 config 目录存在
            Files.createDirectories(yamlPath.getParent());
            
            // 写入 YAML 文件
            Files.writeString(yamlPath, yamlContent);
            log.info("✅ Generated config.yaml for repo: {} at: {}", repoUrl, yamlPath);
            
            // 同时生成 .env 文件以保持兼容性
            String envContent = buildEnvContent(config);
            Files.writeString(envPath, envContent);
            log.info("✅ Generated .env for repo: {} at: {}", repoUrl, envPath);
            
            log.debug("Environment: {}, Config keys: {}", envName != null ? envName : "default", config.keySet());
            
            return true;

        } catch (IOException e) {
            log.error("❌ Failed to generate config files for repo: {}", repoUrl, e);
            return false;
        }
    }

    /**
     * 获取配置信息
     * <p>
     * 优先级：
     * 1. 从 SkillConfigProperties 读取（Spring @Value / YAML 配置）
     * 2. 从 AI 中台 API 获取（TODO）
     * 3. 使用默认配置模板
     *
     * @param repoUrl Git 仓库地址
     * @param envName 环境名称
     * @return 配置映射
     */
    private Map<String, String> getConfig(String repoUrl, String envName) {
        // 1. 尝试从缓存获取
        String cacheKey = repoUrl + ":" + (envName != null ? envName : "default");
        Map<String, String> cached = configCache.get(cacheKey);
        if (cached != null) {
            log.debug("Using cached config for: {}", cacheKey);
            return cached;
        }

        Map<String, String> config;

        // 2. 优先从 Spring 配置读取（@Value / application.yml）
        if (skillConfig != null) {
            log.info("✅ Using Spring configuration (application.yml / @Value)");
            config = skillConfig.toFlatMap();
        } else {
            // 3. TODO: 从 AI 中台获取配置
            // config = fetchFromAIPlatform(repoUrl, envName);
            // if (config != null && !config.isEmpty()) {
            //     log.info("✅ Fetched config from AI platform");
            // } else {
                // 4. 使用默认配置模板
                log.warn("⚠️ Using default config template for repo: {}. Please configure in application.yml or AI platform.", repoUrl);
                config = new ConcurrentHashMap<>(DEFAULT_CONFIG_TEMPLATE);
                resolvePlaceholders(config);
            // }
        }

        configCache.put(cacheKey, config);
        return config;
    }

    /**
     * 构建 YAML 数据结构
     * 优先使用 Spring 配置，否则从扁平配置转换
     *
     * @param config 配置映射
     * @return YAML 数据结构
     */
    private Map<String, Object> buildYamlStructure(Map<String, String> config) {
        // 如果 Spring 配置可用，直接使用分层结构
        if (skillConfig != null) {
            return skillConfig.toNestedMap();
        }
        
        // 否则从扁平配置转换
        Map<String, Object> root = new LinkedHashMap<>();
        
        // 数据库配置 - 数据查询统计库
        Map<String, Object> database = new LinkedHashMap<>();
        database.put("host", getValue(config, "DB_HOST"));
        database.put("port", getIntValue(config, "DB_PORT"));
        database.put("name", getValue(config, "DB_NAME"));
        database.put("user", getValue(config, "DB_USER"));
        database.put("password", getValue(config, "DB_PASSWORD"));
        root.put("database", database);
        
        // DataPlatform 数据库配置
        Map<String, Object> dataplatform = new LinkedHashMap<>();
        dataplatform.put("host", getValue(config, "DP_HOST"));
        dataplatform.put("port", getIntValue(config, "DP_PORT"));
        dataplatform.put("name", getValue(config, "DP_NAME"));
        dataplatform.put("user", getValue(config, "DP_USER"));
        dataplatform.put("password", getValue(config, "DP_PASSWORD"));
        root.put("dataplatform", dataplatform);
        
        // 对话存储数据库配置
        Map<String, Object> conversationDb = new LinkedHashMap<>();
        conversationDb.put("host", getValue(config, "CONVERSATION_DB_HOST"));
        conversationDb.put("port", getIntValue(config, "CONVERSATION_DB_PORT"));
        conversationDb.put("name", getValue(config, "CONVERSATION_DB_NAME"));
        conversationDb.put("user", getValue(config, "CONVERSATION_DB_USER"));
        conversationDb.put("password", getValue(config, "CONVERSATION_DB_PASSWORD"));
        root.put("conversation_db", conversationDb);
        
        // 企业微信配置
        Map<String, Object> wecom = new LinkedHashMap<>();
        wecom.put("enabled", getBooleanValue(config, "WECOM_ENABLED"));
        root.put("wecom", wecom);
        
        return root;
    }

    /**
     * 获取配置值（去除占位符格式）
     */
    private String getValue(Map<String, String> config, String key) {
        String value = config.getOrDefault(key, "");
        // 如果是 ${KEY:default} 格式，提取默认值
        if (value.startsWith("${") && value.endsWith("}")) {
            int colonIndex = value.indexOf(':');
            if (colonIndex > 0) {
                return value.substring(colonIndex + 1, value.length() - 1);
            }
            return value.substring(2, value.length() - 1);
        }
        return value;
    }

    /**
     * 获取整数值
     */
    private Object getIntValue(Map<String, String> config, String key) {
        String value = getValue(config, key);
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            return value; // 如果不是数字，返回字符串
        }
    }

    /**
     * 获取布尔值
     */
    private Object getBooleanValue(Map<String, String> config, String key) {
        String value = getValue(config, key);
        return Boolean.parseBoolean(value);
    }

    /**
     * 构建 .env 文件内容
     *
     * @param config 配置映射
     * @return .env 文件内容字符串
     */
    private String buildEnvContent(Map<String, String> config) {
        StringBuilder sb = new StringBuilder();
        
        sb.append("# =============================================================================\n");
        sb.append("# Auto-generated by SkillEnvConfigManager\n");
        sb.append("# DO NOT commit this file to version control!\n");
        sb.append("# Generated at: ").append(java.time.Instant.now()).append("\n");
        sb.append("# =============================================================================\n\n");

        // 数据库配置 - 数据查询统计库
        sb.append("# -----------------------------------------------------------------------------\n");
        sb.append("# 数据查询统计数据库配置（原有配置）\n");
        sb.append("# -----------------------------------------------------------------------------\n");
        appendConfig(sb, config, "DB_HOST", "DB_PORT", "DB_NAME", "DB_USER", "DB_PASSWORD");
        sb.append("\n");

        // 数据库配置 - DataPlatform 库
        sb.append("# -----------------------------------------------------------------------------\n");
        sb.append("# DataPlatform 数据库配置（etl_order_data_daily 所在库）\n");
        sb.append("# -----------------------------------------------------------------------------\n");
        appendConfig(sb, config, "DP_HOST", "DP_PORT", "DP_NAME", "DP_USER", "DP_PASSWORD");
        sb.append("\n");

        // 数据库配置 - 对话存储库
        sb.append("# -----------------------------------------------------------------------------\n");
        sb.append("# 对话存储数据库配置（新增，独立数据库）\n");
        sb.append("# -----------------------------------------------------------------------------\n");
        appendConfig(sb, config, "CONVERSATION_DB_HOST", "CONVERSATION_DB_PORT", 
                     "CONVERSATION_DB_NAME", "CONVERSATION_DB_USER", "CONVERSATION_DB_PASSWORD");
        sb.append("\n");

        // 企业微信开关
        sb.append("# -----------------------------------------------------------------------------\n");
        sb.append("# 企微机器人开关（本地调试时设为 false，避免与线上服务抢占连接）\n");
        sb.append("# -----------------------------------------------------------------------------\n");
        sb.append("WECOM_ENABLED=").append(config.getOrDefault("WECOM_ENABLED", "true")).append("\n");

        return sb.toString();
    }

    /**
     * 追加配置项到 StringBuilder
     */
    private void appendConfig(StringBuilder sb, Map<String, String> config, String... keys) {
        for (String key : keys) {
            String value = config.getOrDefault(key, "");
            sb.append(key).append("=").append(value).append("\n");
        }
    }

    /**
     * 解析配置中的占位符
     * 优先使用系统属性，其次使用环境变量，最后使用默认值
     *
     * @param config 配置映射
     */
    private void resolvePlaceholders(Map<String, String> config) {
        config.replaceAll((key, value) -> {
            if (value.startsWith("${") && value.endsWith("}")) {
                // 解析 ${KEY:default} 格式
                String content = value.substring(2, value.length() - 1);
                int colonIndex = content.indexOf(':');
                
                String envKey;
                String defaultValue;
                
                if (colonIndex > 0) {
                    envKey = content.substring(0, colonIndex);
                    defaultValue = content.substring(colonIndex + 1);
                } else {
                    envKey = content;
                    defaultValue = "";
                }
                
                // 优先使用系统属性
                String systemValue = System.getProperty(envKey);
                if (systemValue != null && !systemValue.isEmpty()) {
                    return systemValue;
                }
                
                // 其次使用环境变量
                String envValue = System.getenv(envKey);
                if (envValue != null && !envValue.isEmpty()) {
                    return envValue;
                }
                
                // 最后使用默认值
                return defaultValue;
            }
            return value;
        });
    }

    /**
     * TODO: 从 AI 中台获取配置
     * 这个方法需要实现实际的 HTTP 调用逻辑
     *
     * @param repoUrl Git 仓库地址
     * @param envName 环境名称
     * @return 配置映射，null 表示获取失败
     */
    private Map<String, String> fetchFromAIPlatform(String repoUrl, String envName) {
        // TODO: 实现实际的 API 调用
        // 示例：
        // String apiUrl = "https://ai-platform.example.com/api/skill/config";
        // String url = apiUrl + "?repo=" + URLEncoder.encode(repoUrl) + "&env=" + envName;
        // 
        // HttpClient client = HttpClient.newHttpClient();
        // HttpRequest request = HttpRequest.newBuilder()
        //     .uri(URI.create(url))
        //     .header("Authorization", "Bearer " + getAuthToken())
        //     .GET()
        //     .build();
        // 
        // HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
        // 
        // if (response.statusCode() == 200) {
        //     return parseJsonToMap(response.body());
        // }
        
        log.debug("AI platform config fetch not implemented yet for repo: {}", repoUrl);
        return null;
    }

    /**
     * 清除配置缓存
     *
     * @param repoUrl Git 仓库地址，null 表示清除所有
     */
    public void clearCache(String repoUrl) {
        if (repoUrl == null || repoUrl.isBlank()) {
            configCache.clear();
            log.info("Cleared all config cache");
        } else {
            configCache.entrySet().removeIf(entry -> entry.getKey().startsWith(repoUrl + ":"));
            log.info("Cleared config cache for repo: {}", repoUrl);
        }
    }

    /**
     * 更新配置（用于动态刷新）
     *
     * @param repoUrl Git 仓库地址
     * @param envName 环境名称
     * @param config  新配置
     */
    public void updateConfig(String repoUrl, String envName, Map<String, String> config) {
        String cacheKey = repoUrl + ":" + (envName != null ? envName : "default");
        configCache.put(cacheKey, new ConcurrentHashMap<>(config));
        log.info("Updated config for: {}", cacheKey);
    }
}
