package org.example.agentScope.util.skill;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

/**
 * 技能仓库 .env 文件生成器
 * <p>
 * 在 Git 仓库克隆完成后，自动生成 skills/config/.env 文件，
 * 将 Spring 配置中的数据库等配置传递给 Python 脚本。
 *
 * @author AgentScope-Team
 */
@Slf4j
@Component
public class SkillEnvGenerator {

    private final SkillConfigProperties skillConfigProperties;

    public SkillEnvGenerator(SkillConfigProperties skillConfigProperties) {
        this.skillConfigProperties = skillConfigProperties;
    }

    /**
     * 在技能仓库根目录下生成 skills/config/.env 文件
     *
     * @param repoRoot 技能仓库根目录（临时目录）
     * @return 是否生成成功
     */
    public boolean generateEnvFile(Path repoRoot) {
        Path envPath = repoRoot.resolve("skills").resolve("config").resolve(".env");

        try {
            // 确保 config 目录存在
            Files.createDirectories(envPath.getParent());

            // 生成 .env 内容
            String envContent = buildEnvContent();

            // 写入文件（覆盖已有文件）
            Files.writeString(envPath, envContent, StandardCharsets.UTF_8);

            log.info("✅ Generated .env file at: {}", envPath);
            return true;
        } catch (IOException e) {
            log.error("❌ Failed to generate .env file at: {}", envPath, e);
            return false;
        }
    }

    /**
     * 构建 .env 文件内容
     */
    private String buildEnvContent() {
        Map<String, String> config = skillConfigProperties.toFlatMap();

        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by SkillEnvGenerator\n");
        sb.append("# Do not edit manually - changes will be overwritten\n\n");

        // 数据库配置
        sb.append("# 数据查询统计数据库配置\n");
        appendConfig(sb, config, "DB_HOST");
        appendConfig(sb, config, "DB_PORT");
        appendConfig(sb, config, "DB_NAME");
        appendConfig(sb, config, "DB_USER");
        appendConfig(sb, config, "DB_PASSWORD");
        sb.append("\n");

        // DataPlatform 配置
        sb.append("# DataPlatform 数据库配置\n");
        appendConfig(sb, config, "DP_HOST");
        appendConfig(sb, config, "DP_PORT");
        appendConfig(sb, config, "DP_NAME");
        appendConfig(sb, config, "DP_USER");
        appendConfig(sb, config, "DP_PASSWORD");
        sb.append("\n");

        // 对话存储数据库配置
        sb.append("# 对话存储数据库配置\n");
        appendConfig(sb, config, "CONVERSATION_DB_HOST");
        appendConfig(sb, config, "CONVERSATION_DB_PORT");
        appendConfig(sb, config, "CONVERSATION_DB_NAME");
        appendConfig(sb, config, "CONVERSATION_DB_USER");
        appendConfig(sb, config, "CONVERSATION_DB_PASSWORD");
        sb.append("\n");

        // 企业微信配置
        sb.append("# 企业微信配置\n");
        appendConfig(sb, config, "WECOM_ENABLED");

        return sb.toString();
    }

    private void appendConfig(StringBuilder sb, Map<String, String> config, String key) {
        String value = config.get(key);
        if (value != null) {
            sb.append(key).append("=").append(value).append("\n");
        }
    }
}
